### ISSUE TITLE
AIUTO PER FAVORE

### ISSUE THREAD

**Issue by eliafirenze** [KennyRotella/subito_bot#1]
Ciao avresti modo di creare un bot capace di rinnovare gli annunci di Subito.it?

**Comment by KennyRotella** [comment]
ciao Elia, certo questa repo contiene un bot che serve a questo, ti basterà seguire le istruzioni del readme, premetto che non è perfetto, quindi in casi eccezionali potrebbe non funzionare, fammi sapere a quale punto non riesci a procedere o in caso di dubbi

**Comment by eliafirenze** [comment]
> ciao Elia, certo questa repo contiene un bot che serve a questo, ti basterà seguire le istruzioni del readme, premetto che non è perfetto, quindi in casi eccezionali potrebbe non funzionare, fammi sapere a quale punto non riesci a procedere o in caso di dubbi

il punto è che non ci so smanettare più di tanto, tu saresti così gentile da indicarmi qualche tutorial di un lavoro simile per favore?

**Comment by KennyRotella** [comment]
non conosco altri progetti, per questo ne ho voluto fare uno io.. puoi scaricare il bot già pronto da questo link (https://github.com/KennyRotella/subito_bot/releases/download/Latest/Windows.portable.zip)

**Comment by KennyRotella** [comment]
prova ad eseguirlo e ad inserire un annuncio, è intuitivo, fai riferimento alla pagina di subito e compila solo i campi che ti interessano, alcuni campi sono in più e puoi lasciarli vuoti, una volta inserite le immagini non le eliminare o spostare in altre cartelle

**Comment by KennyRotella** [comment]
il campo "tipologia", se presente anche su subito, indica il numero dell opzione, quindi se ad esempio vuoi inserire una TV in vendita dovrai metterci "1" come opzione del menù 
![Screenshot_20220430-110836](https://user-images.githubusercontent.com/44784095/166099385-5eed4553-7bf0-4b30-b577-ad0783ffaef7.jpg)

**Comment by KennyRotella** [comment]
con un editor di testo dovrai inserire le tue credenziali nel file "credenziali.ini"
![Uploading Screenshot_20220430-111201__01__01.jpg…]()

**Comment by KennyRotella** [comment]
con un editor di testo dovrai inserire le tue credenziali nel file "credenziali.ini" 
![Screenshot_20220430-111201__01__01](https://user-images.githubusercontent.com/44784095/166099582-b3cb2f79-a2c8-4008-b6ae-629c9de02e4f.jpg)

**Comment by eliafirenze** [comment]
> con un editor di testo dovrai inserire le tue credenziali nel file "credenziali.ini" ![Screenshot_20220430-111201__01__01](https://user-images.githubusercontent.com/44784095/166099582-b3cb2f79-a2c8-4008-b6ae-629c9de02e4f.jpg)

mitico!! più tardi ti faccio sapere se riesco a combinare qualcosa, grazie mille intanto!! apprezzo molto

**Comment by eliafirenze** [comment]
> con un editor di testo dovrai inserire le tue credenziali nel file "credenziali.ini" ![Screenshot_20220430-111201__01__01](https://user-images.githubusercontent.com/44784095/166099582-b3cb2f79-a2c8-4008-b6ae-629c9de02e4f.jpg)

FANTASTICO!!! funziona e fa il suo sporco lavoro, mi hai fatto commuovere te lo giuro ahaha, qualche piccola correzione nell'interfaccia ed è perfetto sto bot!!! Grazie!

**Comment by KennyRotella** [comment]
son felice che possa aiutare anche qualcun altro 😁

**Comment by eliafirenze** [comment]
per ultimissima cosa ti volevo solo chiedere se in futuro hai intenzione di upgradare il bot per poter selezionare e rimuovere meglio le immagini dei vari annunci poi se conosci un searcher bot sempre per subito.it
Grazie ancora

**Comment by KennyRotella** [comment]
non credo di aggiornarlo per il momento, in fondo il suo lavoro lo fa.. poi se qualcuno vuole contribuire sarà il benvenuto 😁 mi spiace, ma non conosco altri bot
